repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --fail-under=8 -f colorized # -r y (for report)
        language: python
        types: [python]
      - id: pytest
        name: pytest
        entry: bash -c 'pytest -v --color=yes tests/'
        language: system
        types: [python]
