# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI Staging

on:
  push:
    branches:
      - "staging"
  pull_request:
    branches:
      - "staging"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Debug step
        run: pipenv run python3 -c 'import platformdirs'

      - name: Lint with black
        run: |
          pipenv run black .

      - name: Run pylint
        run: |
          pipenv run pylint main.py
          pipenv run pylint lib/

      - name: Test with Pytest
        run: |
          pipenv run pytest tests/
