# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches:
      - "main"
      - "staging"
  pull_request:
    branches:
      - "main"
      - "staging"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Lint with black
        run: |
          pipenv run black .

      - name: Run pylint
        run: |
          pipenv run pylint main.py
          pipenv run pylint lib/

      - name: Test with Pytest
        run: |
          pipenv run pytest tests/
